### ISSUE TITLE
Why is there a warning for this module? What does this do

### ISSUE THREAD

**Issue by Abinpj1** [mahisataruna/Kreapic-Disable-Thermal#1]
Hey care to explain what this does or why you mentioned to use it wisely

**Comment by safarov399** [comment]
As you may have already realized, phones do not have built-in coolers (with a couple of ZTE gaming phones being an exception), making cooling a hassle. That is why, the manufacturers use throttling as a mean to cool and limit the maximum temperature the SoC and the battery can reach. This module just disables those features and allows the phone SoC to run with its maximum performance at all times. The drawback is that the phone gets extremely hot and as a result, it may get permanently damaged.
